package sensor;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.net.SocketException;
import java.util.HashMap;
import java.net.Socket;

public class Sensor {
	
	private Socket socket;
	private ObjectOutputStream sensorDataOutput;
	@SuppressWarnings("unused")	// ObjectInputStream has to be there even if it's not used.
	private ObjectInputStream serverDataInput;
	@SuppressWarnings("unused")
	private PrintWriter sensorTextOutput;
	private BufferedReader sensorTextInput;
	private long lastUpdate = 0;
	
	/*
	 * check if the sensor has an active connection with the target server.
	 */
	public boolean isConnected() {
		return socket.isConnected();
	}
	
	/*
	 * returns the time that the sensor made a call on writeObject method,
	 * in milliseconds; generated by using System.currentTime()
	 */
	public long getLastUpdate() {
		return lastUpdate;
	}

	/*
	 * when a sensor calls writeObject method, we record the system time,
	 * at that moment in milliseconds using System.currentTime()
	 */
	public void setLastUpdate(long lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	/*
	 * establishes connection with the given host on the given port.
	 */
	public boolean connectToServer(String host, int port) {
		boolean connected = false;
		
		// attempt connection.
		try {
			this.socket = new java.net.Socket(host, port);
			
			// initiate I/O streams.
			this.sensorDataOutput = new ObjectOutputStream(socket.getOutputStream());
			this.serverDataInput = new ObjectInputStream(socket.getInputStream());
			this.sensorTextOutput = new PrintWriter(socket.getOutputStream(), true);
			this.sensorTextInput = new BufferedReader(new InputStreamReader(socket.getInputStream()));
			
			connected = true;
		} catch (IOException e) {
			e.printStackTrace();
		}
		
		return connected;
	}
	
	public boolean disconnectFromServer() {
		boolean disconnected= false;
		
		if (socket != null) {
			try {
				socket.close();
				disconnected = true;
			}
			catch (IOException e) {
				e.printStackTrace();
			}
		}
		
		return disconnected;
	}
	
	/*
	 * we can send a HashMap of data using this method.
	 * this method will write to the ObjectOutputStream of the socket itself,
	 * and can be read from the ObjectInputStream at the server's end.
	 */
	public boolean writeObject(HashMap<String, String> data) {
		boolean wrote = false;
		try {
			sensorDataOutput.writeObject(data);
			setLastUpdate(System.currentTimeMillis());
			
			wrote = true;
		}
		catch (SocketException e) {
			disconnectFromServer();
			// this mostly means the server is no longer running and the pipe is broken as a result.
			// so there's no point of staying connected.
			System.err.println("Server down, disconnected and exiting..");
			System.exit(1);
		}
		catch (IOException e) {
			e.printStackTrace();
		} 
		
		return wrote;
	}
	
	public void writeText(String text) {
		sensorTextOutput.println(text);
	}
	
	public String readText() {
		try {
			return sensorTextInput.readLine();
		} catch (IOException e) {
			return null;
		}
	}
}
